// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(PollContext))]
    [Migration("20221125150034_MigrationV3")]
    partial class MigrationV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poll");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Are you a programmer?"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Do you like dogs?"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Do you like coffee?"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.VoteOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoteAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("VoteOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PollId = 1,
                            Title = "yes",
                            VoteAmount = 5
                        },
                        new
                        {
                            Id = 2,
                            PollId = 1,
                            Title = "no",
                            VoteAmount = 2
                        },
                        new
                        {
                            Id = 3,
                            PollId = 1,
                            Title = "ofcourse!",
                            VoteAmount = 8
                        },
                        new
                        {
                            Id = 4,
                            PollId = 2,
                            Title = "yes sirr",
                            VoteAmount = 28
                        },
                        new
                        {
                            Id = 5,
                            PollId = 2,
                            Title = "no i like turtles",
                            VoteAmount = 10
                        },
                        new
                        {
                            Id = 6,
                            PollId = 2,
                            Title = "ofcourse i do!",
                            VoteAmount = 5
                        },
                        new
                        {
                            Id = 7,
                            PollId = 3,
                            Title = "YES",
                            VoteAmount = 50
                        },
                        new
                        {
                            Id = 8,
                            PollId = 3,
                            Title = "NO",
                            VoteAmount = 14
                        },
                        new
                        {
                            Id = 9,
                            PollId = 3,
                            Title = "I'm addicted to it!",
                            VoteAmount = 75
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.VoteOption", b =>
                {
                    b.HasOne("WebApplication1.Models.Poll", "Poll")
                        .WithMany("VoteOptions")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("WebApplication1.Models.Poll", b =>
                {
                    b.Navigation("VoteOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
